version: '3'

includes:
  snow-cli:
    taskfile: ./tasks/snow-cli/snowcli-tasks.yml
    dir: ./tasks/snow-cli

  test-snow-connection:
    desc: Test the Snowflake CLI connection.
    cmds:
      - task: snow-cli:test-snow-connection
        vars:
          CLI_CONNECTION_NAME: $CLI_CONNECTION_NAME
